baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Segnet'

google_analytics_id: 'UA-178417050-1'
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/240.png"
  desktop_height: "36px"
footer:
  copyright_text: 'SEGNET &#169;'

seo:
  meta_og_title: "Segent"
  meta_og_type: "website"
  meta_og_url: "https://segnet.co.ke"
  meta_og_image: ""
  meta_og_description: "We provide provide services that nurture local groups."
  meta_twitter_card: "summary"
  meta_twitter_site: null
  meta_twitter_creator: null

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
